<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">        
    </head>
    <body>
        
        <div id="wrapper">
            <div class="header">
                
            </div>
            
            <div class="container">
                <?php echo $this->content; ?>
                <hr>            
            </div> <!-- /container -->
            
            <div class="footer">
                <footer>
                    
                </footer>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
